### ISSUE TITLE
Prior connectivity matrix

### ISSUE THREAD

**Issue by poorvam** [flatironinstitute/inferelator_sc#54]
Hi,

How do I create prior connectivity matrix for gene and TF, is it required to be binary? If not what scores to be used? I have RNAseq and ATACseq data.

Thanks,
Poorva

**Comment by asistradition** [comment]
The prior knowledge matrix [genes x tfs] can be either a weighted or unweighted and signed or unsigned connectivity matrix. Typically I use an unsigned, unweighted (binary) network, but that's mostly because it's hard enough to build already and I don't want to try to deal with weighting & signing as well.

As for how to build it, it should be what you know about the regulatory network now. I've used literature-derived prior networks (e.g. building from a database of known connections that have been shown experimentally), and they work well. I've also used TF PWM motifs to search for regulatory connections, but that tends to be pretty noisy. There's some promising work using deep learning to identify TF regulators (e.g. https://www.nature.com/articles/s41588-021-00782-6) that's worth considering as well.
